---
- hosts: windows
  gather_facts: False

  pre_tasks:

    - name: gather facts
      setup:


  roles:
     - {
        role: "sa_gitlab_runner_win",
        gitlab_runner_registration_token: "SPECIFY"
       }

  tasks:

    - debug: msg="Tasks section"
